"""
Copyright (C) 2026 Casper Steinmann
"""
from __future__ import annotations
from typing import Protocol, List, Tuple, Iterable, Optional


class AtomProtocol(Protocol):
    def get_idx(self) -> int: ...
    def get_id(self) -> int: ...
    def get_atomic_num(self) -> int: ...
    def get_type(self) -> str: ...
    def get_formal_charge(self) -> int: ...
    def set_formal_charge(self, charge: int) -> None: ...
    def get_implicit_h_count(self) -> int: ...
    def set_implicit_h_count(self, count: int) -> None: ...
    def get_explicit_degree(self) -> int: ...
    def get_implicit_valence(self) -> int: ...
    def is_hbond_donor_h(self) -> bool: ...
    def is_hbond_donor(self) -> bool: ...
    def is_hbond_acceptor(self) -> bool: ...
    def is_connected(self, other: AtomProtocol) -> bool: ...
    def get_distance(self, other: AtomProtocol) -> float: ...
    def get_angle(self, a1: AtomProtocol, a2: AtomProtocol) -> float: ...
    def set_position(self, x: float, y: float, z: float) -> None: ...
    def get_position(self) -> Tuple[float, float, float]: ...
    def iter_neighbors(self) -> Iterable[AtomProtocol]: ...


class BondProtocol(Protocol):
    def get_bond_order(self) -> int: ...


class ResidueProtocol(Protocol):
    def get_name(self) -> str: ...
    def get_atom_id(self, atom: AtomProtocol) -> str: ...
    def get_num_atoms(self) -> int: ...
    def iter_atoms(self) -> Iterable[AtomProtocol]: ...


class MoleculeProtocol(Protocol):
    def num_atoms(self) -> int: ...
    def get_atom(self, idx: int) -> AtomProtocol: ...
    def delete_atom(self, atom: AtomProtocol) -> None: ...
    def add_atom(self, atom: AtomProtocol) -> bool: ...
    def duplicate_atom(self, source: AtomProtocol) -> AtomProtocol: ...
    def get_bond(self, idx1: int, idx2: int) -> Optional[BondProtocol]: ...
    def delete_bond(self, bond: BondProtocol) -> None: ...
    def find_children(self, a1: int, a2: int) -> List[int]: ...
    def add_hydrogens_to_atom(self, atom: AtomProtocol) -> bool: ...
    def iter_residues(self) -> Iterable[ResidueProtocol]: ...


class SmartsMatcherProtocol(Protocol):
    def match(self, mol: MoleculeProtocol, pattern: str) -> List[Tuple[int, ...]]: ...


class ChargeModelProtocol(Protocol):
    def compute_charges(self, mol: MoleculeProtocol) -> bool: ...
    def get_partial_charges(self) -> List[float]: ...


class ToolkitAdapterProtocol(Protocol):
    def read_molecule(self, filename: str) -> MoleculeProtocol: ...
    def make_smarts_matcher(self) -> SmartsMatcherProtocol: ...
    def make_charge_model(self, model_name: str) -> ChargeModelProtocol: ...
    def make_empty_atom(self) -> AtomProtocol: ...
